go_version: 1.25.6
caddy_version: v2.10.2
caddy_cloudflare_version: v0.2.2

caddy_revserse_proxies:
  - subdomain: bitwarden
    tailnet_node: homelab-bitwarden
    port: 80
  - subdomain: freshrss
    tailnet_node: homelab-freshrss
    port: 80
  - subdomain: nextcloud
    tailnet_node: homelab-nextcloud
    port: 8080
  - subdomain: immich
    tailnet_node: homelab-immich
    port: 2283
  - subdomain: n8n
    tailnet_node: homelab-n8n
    port: 5678
  - subdomain: paperless
    tailnet_node: homelab-paperless
    port: 8000
