go_version: 1.26.0
caddy_version: v2.11.1
caddy_cloudflare_version: v0.2.3
caddy_netcup_version: v1.0.0
caddy_porkbun_version: v0.3.1

caddy_revserse_proxies:
  - subdomain: bitwarden
    tailnet_node: homelab-bitwarden
    port: 80
  - subdomain: freshrss
    tailnet_node: homelab-freshrss
    port: 80
  - subdomain: nextcloud
    tailnet_node: homelab-nextcloud
    port: 8080
  - subdomain: immich
    tailnet_node: homelab-immich
    port: 2283
  - subdomain: n8n
    tailnet_node: homelab-n8n
    port: 5678
  - subdomain: paperless
    tailnet_node: homelab-paperless
    port: 8000

caddy_reverse_proxies_ext:
  - subdomain: links
    tailnet_node: homelab-homepage-ext
    port: 3000
