cloudflare_api_token: ENC[AES256_GCM,data:BCcU5McIZoX5i+a1WyPU4VJZ9vQ6dhsC98U+WU4YsdVniOUCDJl9vQ==,iv:GYea6Avtnn4OJm2QXtsYtAGA3wDpS75ndczkm2idT98=,tag:ffdVMObcfxRaqrXAR6MitA==,type:str]
service_domain: ENC[AES256_GCM,data:7rQH8RS4HSmha3VM,iv:ZltJOz0pZFxZ0sUB+ETOjwndxrWuf3/Mu1Le3NsyvPI=,tag:TmLiURbYFF8yxkpggwweDw==,type:str]
tailnet_domain: ENC[AES256_GCM,data:LsV534sz4lfnLTjGzMV6pg==,iv:NUGW6QYrIK2KtdI1gMsHbNkV58nETQFQ2dpqr7a+GDM=,tag:X1/5iw7Komx2NALVn76hQQ==,type:str]
ext_domain_1: ENC[AES256_GCM,data:FmDNXQquptxj,iv:vwltuaLpwIp8GNs49G5s2zTaTrL8A3he2dLoJ+Bjjus=,tag:s2DFMvFyB3VklRd3Xf/o1g==,type:str]
netcup_customer_number: ENC[AES256_GCM,data:cSXT8y+L,iv:cNiA70AN2NiXh/fROWkPaA2la5zlwnARLbyvedsH6Qc=,tag:sGkg3ElfcW6/SXPbxzKwMg==,type:int]
netcup_api_key: ENC[AES256_GCM,data:h0Lwm8ZZrgJixZSIn8iS6zFMfDr0zlZKP99KZKj9Om/ra8/3CtyWF+5JiVCOOATrMXY=,iv:vgjFtFZoKeQgJJ8jGiJNr+JBmOfa7hICZr3mVBNy2eY=,tag:7lGj0lh2B1fW5DKzwl/rAA==,type:str]
netcup_api_password: ENC[AES256_GCM,data:WjqVXY06DnzlwoLvKRYmwD4IiN+lwQJY+ZeUOOyBbgcVh49TZcYVdSIPbKknko0i1EE=,iv:JDCQ2W5pgxG0qHXqds8u8bXldBOdvtPFo6etKqo6I/U=,tag:4k3RFqMA+Wfq/paEtxCG0A==,type:str]
ext_domain_2: ENC[AES256_GCM,data:C+bevSCmt+I=,iv:Y6OOv4yYYlr/n3EUyHHOc70M+7pZfI+KQnodK4THOkc=,tag:nCA0REU+edePxvutSvCR0g==,type:str]
porkbun_api_key: ENC[AES256_GCM,data:wzBOavgp629DDEBGHzAjrr4EjYQbfvYs6UCqA30yOmGLKhk1IKVBwgg3hmYX+eoryoPtnK8uULQzTRE9fSy7GdZewj8=,iv:sHBMWOUReaZnoV0uxm61HHf4Deh408Urd0pLeaey44s=,tag:2lCjzL9Z4PbAeuiklU9QJQ==,type:str]
porkbun_api_secret_key: ENC[AES256_GCM,data:3kCdqnIArz0wQTldWTxaPCI/o8r9DMGQCCmMFrgpvhSi0zaylrqdCSzFgrj2lYpNrl1ClwSFW9iR1XzLaVaFvn9kdqM=,iv:0PJ1M0uB4eHkNBA/BGghUudmNZFehVNhI9+Cs8b7d40=,tag:oXzUxFISPRaoKZvmLpsm6w==,type:str]
public_ip: ENC[AES256_GCM,data:c3iSCWY8le6p/nlPjQ==,iv:0e7MiYEIPsc4w1w3j4Bb9LnS3kpufD99WzvGoICTkC0=,tag:LMrXBglZD5Xrb28cET3zoQ==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdURPdG1PYW5JZmpocnh4
            NHJaQ1pob0ZEWEo0ajR2czFOREIrSm5kUDA0Cmx2Qy9wdU9HVE84NGg3SmZ4RENv
            cWttSm9GZE8vbFEvdXYvT0NmeDArUE0KLS0tIDlIZlJEV2NMZFZFL2xRdC95ZTYy
            dlBjTFplUkRqZitYYUpoTVNjcXFNTzAKeAZCjBb9b+qKxiBYfBygQ57RnlWz5eVo
            g5a03dK/KUM4JRfAgaxUcTYJWUzIGgx0rx/V/yNMDXnkb6YmuIbEWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:59:41Z"
    mac: ENC[AES256_GCM,data:QBtazAfvKQzeyFfVrVe2CHBSaQICeZZ3kko7RcBho6VVqUxQU7aSx2SzP9Fabq9IAECqqCg1ZYl6hs2/h7oUvbBe8rmiVmkPJpTgCUqnrqGYakmOPhk+tw7D/jkXW6KxF0+xmmmri+w95pOm0kbuxUVkxbZ7d03s2GcPHYRYJiQ=,iv:Iz44w5+EvKWdVACaITtrhqOvQI7IoFQNRTP5Lfz1yDg=,tag:OZ5gNpzt6iiucqElQhRkpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
