---
- name: pull kube-vip container
  command: "ctr image pull ghcr.io/kube-vip/kube-vip:{{ kube_vip_version }}"
  register: kube_vip_pull_output
  changed_when: "kube_vip_pull_output.stdout is search('total:\\s*0.0\\s*B') == False"

- name: generate kube-vip manifest
  command: >
    ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:{{ kube_vip_version }} vip /kube-vip manifest pod
    --interface {{ interface }}
    --address {{ vip }}
    --controlplane
    --arp
    --leaderElection
  register: kube_vip_manifest
  changed_when: false

- name: modify kube-vip manifest content
  set_fact:
    # https://github.com/kube-vip/kube-vip/issues/684
    modified_kube_vip_manifest: "{{ kube_vip_manifest.stdout | regex_replace('path: /etc/kubernetes/admin.conf', 'path: /etc/kubernetes/super-admin.conf') }}"

- name: write modified kube-vip manifest to file
  copy:
    content: "{{ modified_kube_vip_manifest }}"
    dest: /etc/kubernetes/manifests/kube-vip.yaml
