---
k8s_version: "1.33.1"
# https://containerd.io/releases/#kubernetes-support
containerd_version: "1.7.28"

upgrade_cluster: false

node_ula_prefix: "fd08:192:168:1::"

pod_network_cidr_v4: 172.32.0.0/16
pod_network_cidr_v6: fd08:172:32::/56
service_cidr_v4: 172.16.0.0/24
service_cidr_v6: fd08:172:16::/112

kube_vip_version: v1.0.4
vip: 192.168.1.210
interface: eth0

calico_version: v3.30.2
# range: [20:32]
calico_node_subnet_prefix_length_v4: 24
# range: [116:128]
calico_node_subnet_prefix_length_v6: 120

reset_cluster: false
reset_confirmation: ""
